version: "3.9"

services:
  trading-bot:
    build: .
    container_name: trading-bot
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    command: python src/main.py
